### ISSUE TITLE
Add multi instance

### ISSUE THREAD

**Issue by tcheronneau** [tcheronneau/homers#1]
Add the ability to have multiple instances of each tools

**Comment by tcheronneau** [comment]
Make not much sense to do for others right now.

**Comment by MeticulousLunatic** [comment]
I'd like to request this for specifically Tautulli. I'm going to need to spin up a new Plex server soon and I found varken today in my search for tautulli aggregation options. With it being so obsolete, I'd much rather be able to use this for that instead.

**Comment by tcheronneau** [comment]
Hey @MeticulousLunatic I've moved a bit forward since then and improved a lot the Plex integration. 
From what I've done and test the data is more reliable on Plex directly. 
Would there be any reason on your side to use tautulli instead ? Or having the same info from Plex would work for you ?

**Comment by MeticulousLunatic** [comment]
Hey if it replaces Tautulli by itself then that's awesome and all I'll need, thanks very much and sorry to resurrect the closed topic then
